development:
  adapter: postgresql
  encoding: unicode
  database: race_tracker_development
  pool: 5
  username: andrewsmoker
  password:
  timeout: 5000
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: race_tracker_test
  username: andrewsmoker
  password: 
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>